"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 6.1.

For more information on this file, see
https://docs.djangoproject.com/en/6.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# --------------------------------------------------------------------------
# Настройки из окружения
#
# Всё, что отличается между «у нас на ноутбуке» и «на боевом сервере»,
# берётся из переменных окружения, а не правится в этом файле. Файла
# settings.py по-прежнему один: раздваивать его на dev/prod для проекта
# такого размера — лишняя сложность.
#
# Локально значения удобно держать в файле .env рядом с manage.py
# (он в .gitignore и в репозиторий не попадает). Образец — .env.example.
# Свой мини-парсер, чтобы не тащить ради пяти строк зависимость:
# настоящее окружение всегда главнее файла.
# --------------------------------------------------------------------------

def _load_dotenv(path):
    """Читает KEY=value из .env, не перезаписывая уже заданное окружение."""
    try:
        lines = path.read_text(encoding='utf-8').splitlines()
    except OSError:
        return
    for line in lines:
        line = line.strip()
        if not line or line.startswith('#') or '=' not in line:
            continue
        key, _, value = line.partition('=')
        os.environ.setdefault(key.strip(), value.strip().strip('"\''))


_load_dotenv(BASE_DIR / '.env')


def env_bool(name, default):
    """'1', 'true', 'yes', 'on' (в любом регистре) → True."""
    value = os.environ.get(name)
    if value is None:
        return default
    return value.strip().lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=()):
    """'example.com, www.example.com' → ['example.com', 'www.example.com']."""
    value = os.environ.get(name)
    if not value:
        return list(default)
    return [item.strip() for item in value.split(',') if item.strip()]


# DEBUG по умолчанию включён — чтобы у обоих разработчиков всё
# работало как раньше, без .env и без лишних действий. На боевом
# сервере он выключается переменной DJANGO_DEBUG=0.
DEBUG = env_bool('DJANGO_DEBUG', True)

# Ключ, которым Django подписывает сессии и формы.
# Старый ключ лежал прямо здесь и уехал в публичный репозиторий, то есть
# считается скомпрометированным — для боевого сервера нужно сгенерировать
# новый и положить в DJANGO_SECRET_KEY. Ключ ниже остаётся только для
# локальной разработки и намеренно помечен как небезопасный.
DEV_SECRET_KEY = 'django-insecure-local-only-do-not-use-in-production'
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY') or DEV_SECRET_KEY

if not DEBUG and SECRET_KEY == DEV_SECRET_KEY:
    # Лучше не запуститься совсем, чем тихо работать в проде с ключом,
    # который лежит в открытом репозитории.
    raise ImproperlyConfigured(
        'DJANGO_DEBUG=0, но DJANGO_SECRET_KEY не задан. Сгенерируйте новый '
        'ключ и положите его в переменные окружения — см. .env.example.'
    )

# Домены, с которых сайт отвечает. Локально — сам себе, на боевом
# задаётся через DJANGO_ALLOWED_HOSTS=example.com,www.example.com
ALLOWED_HOSTS = env_list(
    'DJANGO_ALLOWED_HOSTS',
    ['localhost', '127.0.0.1', '[::1]'] if DEBUG else [],
)

# Нужно, когда сайт работает по https за чужим прокси: без этого
# отправка форм (в том числе заявки на просмотр) отвалится по CSRF.
# Значения — со схемой: https://example.com
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

# Настройки https. Включаются одной переменной DJANGO_SECURE_SSL=1 на
# боевом сервере — чтобы при переезде не пришлось править код.
#
# Локально по умолчанию выключены: без сертификата сайт с ними просто
# перестанет открываться (браузер будет бесконечно перебрасывать на
# https://localhost, которого нет).
#
# ВАЖНО: включать только когда сертификат уже работает и сайт реально
# открывается по https. Иначе можно остаться без доступа к собственному
# сайту — особенно из-за HSTS: браузер запоминает «сюда только по https»
# на указанный срок и не даст вернуться обратно.
SECURE_SSL = env_bool('DJANGO_SECURE_SSL', False)

if SECURE_SSL:
    # Перебрасывать http → https.
    SECURE_SSL_REDIRECT = True
    # Куки сессии и CSRF передавать только по шифрованному соединению,
    # чтобы их нельзя было перехватить в открытой сети.
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    # Django стоит за прокси (nginx и т.п.), и о том, что исходный
    # запрос был по https, узнаёт из этого заголовка.
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # HSTS: сколько секунд браузер помнит «этот сайт только по https».
    # Начинать стоит с маленького значения (например, 3600 — час) и
    # поднимать до года, только убедившись, что всё работает.
    SECURE_HSTS_SECONDS = int(os.environ.get('DJANGO_HSTS_SECONDS', '0'))


# Application definition

INSTALLED_APPS = [
    'unfold',  # красивая тема админки, должна идти до django.contrib.admin
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'cars',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.1/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.1/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [BASE_DIR / 'static']

# Куда `manage.py collectstatic` складывает все файлы стилей и скриптов
# (наши из static/ плюс файлы админки и темы unfold) — на боевом сервере
# их отдаёт не Django, а веб-сервер, и он берёт их отсюда. Локально
# папка не нужна и в репозиторий не попадает.
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Uploaded files (car photos)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Admin theme (django-unfold)
# https://unfoldadmin.com/docs/

try:
    ADMIN_OVERRIDES_CSS_VERSION = int(
        (BASE_DIR / 'static' / 'css' / 'admin-overrides.css').stat().st_mtime,
    )
except OSError:
    ADMIN_OVERRIDES_CSS_VERSION = 0

UNFOLD = {
    'SITE_TITLE': 'Premium Cars — админка',
    'SITE_HEADER': 'Premium Cars',
    'SITE_SYMBOL': 'directions_car',
    'SHOW_LANGUAGES': False,
    # Всегда тёмная, приглушённая тема: без переключателя на светлую
    # (у неё белый фон) и без ярко-фиолетового акцента по умолчанию.
    'THEME': 'dark',
    'COLORS': {
        'primary': {
            '50': 'oklch(97% .004 260)',
            '100': 'oklch(94% .008 260)',
            '200': 'oklch(88% .014 260)',
            '300': 'oklch(78% .022 258)',
            '400': 'oklch(64% .035 256)',
            '500': 'oklch(52% .045 255)',
            '600': 'oklch(44% .05 254)',
            '700': 'oklch(37% .045 254)',
            '800': 'oklch(30% .035 255)',
            '900': 'oklch(24% .028 256)',
            '950': 'oklch(17% .02 257)',
        },
    },
    # Приглушаем и цвет текста ошибок (Обязательное поле и т.п.) —
    # у него в теме свой, отдельный от 'primary' насыщенный красный,
    # который отдельным CSS-файлом переопределяется мягче.
    #
    # ?v=... — cache-busting: без этого браузер может годами отдавать
    # старую версию файла из кеша при обычном обновлении страницы
    # (владелец так и увидел серую кнопку «Опубликовать» вместо зелёной
    # и дашборд без стилей — файл на диске уже новый, но в браузере
    # лежал старый, 2026-09-03). ADMIN_OVERRIDES_CSS_VERSION ниже —
    # дата изменения файла на диске, значение в URL меняется само при
    # правке файла, так что каждая правка получает свежую ссылку.
    'STYLES': [f'/static/css/admin-overrides.css?v={ADMIN_OVERRIDES_CSS_VERSION}'],
}


# Email
# https://docs.djangoproject.com/en/6.1/topics/email/#topic-email-configuration

MAILERS = {
    'default': {
        'BACKEND': 'django.core.mail.backends.console.EmailBackend',
    },
}
