# Generated by Django 6.1 on 2026-08-29 23:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50, verbose_name='Марка')),
                ('model', models.CharField(max_length=80, verbose_name='Модель')),
                ('year', models.PositiveSmallIntegerField(verbose_name='Год выпуска')),
                ('price', models.PositiveIntegerField(verbose_name='Цена')),
                ('mileage_km', models.PositiveIntegerField(verbose_name='Пробег, км')),
                ('fuel', models.CharField(choices=[('petrol', 'Бензин'), ('diesel', 'Дизель'), ('hybrid', 'Гибрид'), ('electric', 'Электро'), ('gas', 'Газ/Бензин')], max_length=10, verbose_name='Топливо')),
                ('transmission', models.CharField(choices=[('automatic', 'Автомат'), ('manual', 'Механика')], max_length=10, verbose_name='Коробка передач')),
                ('engine_capacity', models.DecimalField(blank=True, decimal_places=1, help_text='Пусто — для электромобилей', max_digits=3, null=True, verbose_name='Объём двигателя, л')),
                ('power_hp', models.PositiveSmallIntegerField(verbose_name='Мощность, л.с.')),
                ('drive', models.CharField(choices=[('fwd', 'Передний'), ('rwd', 'Задний'), ('awd', 'Полный')], max_length=3, verbose_name='Привод')),
                ('body', models.CharField(choices=[('sedan', 'Седан'), ('wagon', 'Универсал'), ('suv', 'Внедорожник'), ('crossover', 'Кроссовер'), ('hatchback', 'Хэтчбек'), ('coupe', 'Купе'), ('minivan', 'Минивэн')], max_length=10, verbose_name='Кузов')),
                ('vin', models.CharField(blank=True, max_length=17, verbose_name='VIN')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('status', models.CharField(choices=[('for_sale', 'В продаже'), ('reserved', 'Зарезервирован'), ('sold', 'Продан')], default='for_sale', max_length=10, verbose_name='Статус')),
                ('slug', models.SlugField(blank=True, help_text='Заполняется автоматически, например bmw-530d-2020', max_length=150, unique=True, verbose_name='Адрес страницы (slug)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'Автомобили',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Короткое описание')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('instagram', models.URLField(blank=True, verbose_name='Ссылка на Instagram')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram (@username)')),
                ('whatsapp', models.CharField(blank=True, max_length=30, verbose_name='WhatsApp (номер)')),
                ('currency', models.CharField(choices=[('₴', '₴ (гривна)'), ('$', '$ (доллар)'), ('€', '€ (евро)'), ('zł', 'zł (злотый)')], default='$', max_length=3, verbose_name='Валюта цен')),
            ],
            options={
                'verbose_name': 'автосалон',
                'verbose_name_plural': 'Автосалон',
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя клиента')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефон')),
                ('date', models.DateField(verbose_name='Дата просмотра')),
                ('preferred_time', models.CharField(blank=True, help_text='Например: 15:00 или «после 18:00»', max_length=50, verbose_name='Желаемое время')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='cars/', verbose_name='Фото')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car', verbose_name='Автомобиль')),
            ],
            options={
                'verbose_name': 'фотография',
                'verbose_name_plural': 'Фотографии',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.AddField(
            model_name='car',
            name='dealer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cars', to='cars.dealer', verbose_name='Автосалон'),
        ),
    ]
