# Generated by Django 6.1 on 2026-08-30 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='internal_note',
            field=models.TextField(blank=True, help_text='Видна только в админке, на сайте никогда не показывается.', verbose_name='Внутренняя заметка'),
        ),
    ]
