# Generated by Django 6.1 on 2026-09-03 12:06

import cars.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0002_car_internal_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Пока не отмечено — машина не видна на сайте, даже если сохранена в админке. Отдельно от статуса (в продаже/резерв/продан): статус решает, что написано на странице, «опубликовано» решает, существует ли страница для посетителей вообще.', verbose_name='Опубликовано'),
        ),
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, help_text='mp4, mov или webm, до 100 МБ.', upload_to='cars/videos/', validators=[django.core.validators.FileExtensionValidator(['mp4', 'mov', 'webm']), cars.models.validate_video_size], verbose_name='Видео'),
        ),
    ]
