# Generated by Django 6.1 on 2026-09-03 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_car_is_published_car_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accident',
            field=models.BooleanField(default=False, verbose_name='Был в ДТП'),
        ),
        migrations.AddField(
            model_name='car',
            name='imported_from',
            field=models.CharField(blank=True, help_text='Свободный текст, например: США, Германия, Литва. Пусто, если машина не пригнана.', max_length=50, verbose_name='Пригнан из'),
        ),
        migrations.AddField(
            model_name='car',
            name='negotiable',
            field=models.BooleanField(default=False, verbose_name='Торг уместен'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=4, help_text='Сколько единиц дополнительной валюты за 1 единицу основной (например, при основной $ и дополнительной ₴ — сколько гривен за доллар). Вводится вручную, курс не подтягивается автоматически откуда-либо.', max_digits=10, null=True, verbose_name='Курс обмена'),
        ),
        migrations.AddField(
            model_name='dealer',
            name='secondary_currency',
            field=models.CharField(blank=True, choices=[('₴', '₴ (гривна)'), ('$', '$ (доллар)'), ('€', '€ (евро)'), ('zł', 'zł (злотый)')], help_text='Необязательно. Если заполнено, цена на сайте показывается сразу в двух валютах — курс для пересчёта указывается ниже.', max_length=3, verbose_name='Дополнительная валюта'),
        ),
    ]
