# Generated by Django 6.1 on 2026-09-03 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0004_car_accident_car_imported_from_car_negotiable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='sold_at',
            field=models.DateTimeField(blank=True, help_text='Проставляется автоматически, когда статус впервые становится «Продано» (в том числе через массовое действие «Отметить проданными»). Можно поправить вручную, если дата неточная — при повторном сохранении уже заполненная дата не перезаписывается сама.', null=True, verbose_name='Дата продажи'),
        ),
    ]
