# Generated by Django 6.1 on 2026-09-06 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0005_car_sold_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='dealer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Необязательно. Пока пусто — в шапке сайта и админке показывается текстовое название салона, как сейчас.', upload_to='dealer/', verbose_name='Логотип'),
        ),
    ]
