# Generated by Django 6.1 on 2026-09-06 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0006_dealer_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dealer',
            name='logo',
            field=models.ImageField(blank=True, help_text='Необязательно. Пока пусто — в шапке сайта и админке показывается текстовое название салона, как сейчас. Лучше всего смотрится квадратное изображение — в админке логотип показывается в квадратной иконке.', upload_to='dealer/', verbose_name='Логотип'),
        ),
    ]
